// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by figma_tokens_builder

// ignore_for_file: library_private_types_in_public_api, camel_case_types

import 'package:flutter/material.dart';

class FigmaAvata extends ThemeExtension<FigmaAvata> {
  final double avataCompact;
  final double avataDefault;
  final double avataCard;
  final double avataProfile;
  final double avataHero;

  const FigmaAvata({
    required this.avataCompact,
    required this.avataDefault,
    required this.avataCard,
    required this.avataProfile,
    required this.avataHero,
  });

  static const desktop = FigmaAvata(
    avataCompact: 32.0,
    avataDefault: 48.0,
    avataCard: 64.0,
    avataProfile: 80.0,
    avataHero: 96.0,
  );

  static const mobile = FigmaAvata(
    avataCompact: 32.0,
    avataDefault: 48.0,
    avataCard: 48.0,
    avataProfile: 64.0,
    avataHero: 96.0,
  );

  static const tablet = FigmaAvata(
    avataCompact: 32.0,
    avataDefault: 48.0,
    avataCard: 64.0,
    avataProfile: 80.0,
    avataHero: 96.0,
  );

  /// Retrieve the nearest [FigmaAvata] from the widget tree.
  static FigmaAvata of(BuildContext context) {
    return Theme.of(context).extension<FigmaAvata>()!;
  }

  @override
  FigmaAvata copyWith({
    double? avataCompact,
    double? avataDefault,
    double? avataCard,
    double? avataProfile,
    double? avataHero,
  }) {
    return FigmaAvata(
      avataCompact: avataCompact ?? this.avataCompact,
      avataDefault: avataDefault ?? this.avataDefault,
      avataCard: avataCard ?? this.avataCard,
      avataProfile: avataProfile ?? this.avataProfile,
      avataHero: avataHero ?? this.avataHero,
    );
  }

  @override
  FigmaAvata lerp(covariant FigmaAvata? other, double t) {
    if (other == null) return this;
    return FigmaAvata(
      avataCompact: avataCompact + (other.avataCompact - avataCompact) * t,
      avataDefault: avataDefault + (other.avataDefault - avataDefault) * t,
      avataCard: avataCard + (other.avataCard - avataCard) * t,
      avataProfile: avataProfile + (other.avataProfile - avataProfile) * t,
      avataHero: avataHero + (other.avataHero - avataHero) * t,
    );
  }

  @override
  int get hashCode {
    return Object.hash(
      avataCompact,
      avataDefault,
      avataCard,
      avataProfile,
      avataHero,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FigmaAvata) return false;
    return avataCompact == other.avataCompact && avataDefault == other.avataDefault && avataCard == other.avataCard && avataProfile == other.avataProfile && avataHero == other.avataHero;
  }
}

class FigmaIcon extends ThemeExtension<FigmaIcon> {
  final double icoCompact;
  final double icoDefault;
  final double icoLarge;
  final double icoHighlight;
  final double icoStatus;
  final double icoHerohero;

  const FigmaIcon({
    required this.icoCompact,
    required this.icoDefault,
    required this.icoLarge,
    required this.icoHighlight,
    required this.icoStatus,
    required this.icoHerohero,
  });

  static const desktop = FigmaIcon(
    icoCompact: 24.0,
    icoDefault: 32.0,
    icoLarge: 64.0,
    icoHighlight: 64.0,
    icoStatus: 80.0,
    icoHerohero: 96.0,
  );

  static const mobile = FigmaIcon(
    icoCompact: 20.0,
    icoDefault: 24.0,
    icoLarge: 32.0,
    icoHighlight: 48.0,
    icoStatus: 64.0,
    icoHerohero: 80.0,
  );

  static const tablet = FigmaIcon(
    icoCompact: 24.0,
    icoDefault: 32.0,
    icoLarge: 48.0,
    icoHighlight: 64.0,
    icoStatus: 80.0,
    icoHerohero: 96.0,
  );

  /// Retrieve the nearest [FigmaIcon] from the widget tree.
  static FigmaIcon of(BuildContext context) {
    return Theme.of(context).extension<FigmaIcon>()!;
  }

  @override
  FigmaIcon copyWith({
    double? icoCompact,
    double? icoDefault,
    double? icoLarge,
    double? icoHighlight,
    double? icoStatus,
    double? icoHerohero,
  }) {
    return FigmaIcon(
      icoCompact: icoCompact ?? this.icoCompact,
      icoDefault: icoDefault ?? this.icoDefault,
      icoLarge: icoLarge ?? this.icoLarge,
      icoHighlight: icoHighlight ?? this.icoHighlight,
      icoStatus: icoStatus ?? this.icoStatus,
      icoHerohero: icoHerohero ?? this.icoHerohero,
    );
  }

  @override
  FigmaIcon lerp(covariant FigmaIcon? other, double t) {
    if (other == null) return this;
    return FigmaIcon(
      icoCompact: icoCompact + (other.icoCompact - icoCompact) * t,
      icoDefault: icoDefault + (other.icoDefault - icoDefault) * t,
      icoLarge: icoLarge + (other.icoLarge - icoLarge) * t,
      icoHighlight: icoHighlight + (other.icoHighlight - icoHighlight) * t,
      icoStatus: icoStatus + (other.icoStatus - icoStatus) * t,
      icoHerohero: icoHerohero + (other.icoHerohero - icoHerohero) * t,
    );
  }

  @override
  int get hashCode {
    return Object.hash(
      icoCompact,
      icoDefault,
      icoLarge,
      icoHighlight,
      icoStatus,
      icoHerohero,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FigmaIcon) return false;
    return icoCompact == other.icoCompact && icoDefault == other.icoDefault && icoLarge == other.icoLarge && icoHighlight == other.icoHighlight && icoStatus == other.icoStatus && icoHerohero == other.icoHerohero;
  }
}

class _FigmaImage_SizeGroup {
  final double imageThumbnail;
  final double imageList;
  final double imageCard;
  final double imageFeauture;

  const _FigmaImage_SizeGroup({
    required this.imageThumbnail,
    required this.imageList,
    required this.imageCard,
    required this.imageFeauture,
  });

  _FigmaImage_SizeGroup copyWith({
    double? imageThumbnail,
    double? imageList,
    double? imageCard,
    double? imageFeauture,
  }) {
    return _FigmaImage_SizeGroup(
      imageThumbnail: imageThumbnail ?? this.imageThumbnail,
      imageList: imageList ?? this.imageList,
      imageCard: imageCard ?? this.imageCard,
      imageFeauture: imageFeauture ?? this.imageFeauture,
    );
  }

  static _FigmaImage_SizeGroup lerp(_FigmaImage_SizeGroup a, _FigmaImage_SizeGroup b, double t) {
    return _FigmaImage_SizeGroup(
      imageThumbnail: a.imageThumbnail + (b.imageThumbnail - a.imageThumbnail) * t,
      imageList: a.imageList + (b.imageList - a.imageList) * t,
      imageCard: a.imageCard + (b.imageCard - a.imageCard) * t,
      imageFeauture: a.imageFeauture + (b.imageFeauture - a.imageFeauture) * t,
    );
  }
}

class _FigmaImage_RatioGroup {
  final double ratioSquare;
  final double ratioPortrait;
  final double ratioLandspace;
  final double ratioBanner;

  const _FigmaImage_RatioGroup({
    required this.ratioSquare,
    required this.ratioPortrait,
    required this.ratioLandspace,
    required this.ratioBanner,
  });

  _FigmaImage_RatioGroup copyWith({
    double? ratioSquare,
    double? ratioPortrait,
    double? ratioLandspace,
    double? ratioBanner,
  }) {
    return _FigmaImage_RatioGroup(
      ratioSquare: ratioSquare ?? this.ratioSquare,
      ratioPortrait: ratioPortrait ?? this.ratioPortrait,
      ratioLandspace: ratioLandspace ?? this.ratioLandspace,
      ratioBanner: ratioBanner ?? this.ratioBanner,
    );
  }

  static _FigmaImage_RatioGroup lerp(_FigmaImage_RatioGroup a, _FigmaImage_RatioGroup b, double t) {
    return _FigmaImage_RatioGroup(
      ratioSquare: a.ratioSquare + (b.ratioSquare - a.ratioSquare) * t,
      ratioPortrait: a.ratioPortrait + (b.ratioPortrait - a.ratioPortrait) * t,
      ratioLandspace: a.ratioLandspace + (b.ratioLandspace - a.ratioLandspace) * t,
      ratioBanner: a.ratioBanner + (b.ratioBanner - a.ratioBanner) * t,
    );
  }
}

class FigmaImage extends ThemeExtension<FigmaImage> {
  final _FigmaImage_SizeGroup size;
  final _FigmaImage_RatioGroup ratio;

  const FigmaImage({
    required this.size,
    required this.ratio,
  });

  static const mobile = FigmaImage(
    size: _FigmaImage_SizeGroup(
      imageThumbnail: 64.0,
      imageList: 96.0,
      imageCard: 128.0,
      imageFeauture: 160.0,
    ),
    ratio: _FigmaImage_RatioGroup(
      ratioSquare: 0.0,
      ratioPortrait: 0.0,
      ratioLandspace: 0.0,
      ratioBanner: 0.0,
    ),
  );

  static const tablet = FigmaImage(
    size: _FigmaImage_SizeGroup(
      imageThumbnail: 96.0,
      imageList: 128.0,
      imageCard: 160.0,
      imageFeauture: 192.0,
    ),
    ratio: _FigmaImage_RatioGroup(
      ratioSquare: 0.0,
      ratioPortrait: 0.0,
      ratioLandspace: 0.0,
      ratioBanner: 0.0,
    ),
  );

  /// Retrieve the nearest [FigmaImage] from the widget tree.
  static FigmaImage of(BuildContext context) {
    return Theme.of(context).extension<FigmaImage>()!;
  }

  @override
  FigmaImage copyWith({
    _FigmaImage_SizeGroup? size,
    _FigmaImage_RatioGroup? ratio,
  }) {
    return FigmaImage(
      size: size ?? this.size,
      ratio: ratio ?? this.ratio,
    );
  }

  @override
  FigmaImage lerp(covariant FigmaImage? other, double t) {
    if (other == null) return this;
    return FigmaImage(
      size: _FigmaImage_SizeGroup.lerp(size, other.size, t),
      ratio: _FigmaImage_RatioGroup.lerp(ratio, other.ratio, t),
    );
  }

  @override
  int get hashCode {
    return Object.hash(
      size,
      ratio,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FigmaImage) return false;
    return size == other.size && ratio == other.ratio;
  }
}

class FigmaSpacing extends ThemeExtension<FigmaSpacing> {
  final double spaceInlineTight;
  final double spaceInline;
  final double spaceInlineLoose;
  final double spaceComponentGap;
  final double spaceComponentSm;
  final double spaceComponentMd;
  final double spaceComponentLg;
  final double spaceGroup;
  final double spaceGroupLg;
  final double spaceBlock;
  final double spaceBlockLg;
  final double spaceSection;
  final double spaceSectionLg;
  final double screen;

  const FigmaSpacing({
    required this.spaceInlineTight,
    required this.spaceInline,
    required this.spaceInlineLoose,
    required this.spaceComponentGap,
    required this.spaceComponentSm,
    required this.spaceComponentMd,
    required this.spaceComponentLg,
    required this.spaceGroup,
    required this.spaceGroupLg,
    required this.spaceBlock,
    required this.spaceBlockLg,
    required this.spaceSection,
    required this.spaceSectionLg,
    required this.screen,
  });

  static const desktop = FigmaSpacing(
    spaceInlineTight: 4.0,
    spaceInline: 8.0,
    spaceInlineLoose: 12.0,
    spaceComponentGap: 24.0,
    spaceComponentSm: 24.0,
    spaceComponentMd: 32.0,
    spaceComponentLg: 48.0,
    spaceGroup: 16.0,
    spaceGroupLg: 32.0,
    spaceBlock: 16.0,
    spaceBlockLg: 32.0,
    spaceSection: 32.0,
    spaceSectionLg: 64.0,
    screen: 1024.0,
  );

  static const mobile = FigmaSpacing(
    spaceInlineTight: 4.0,
    spaceInline: 8.0,
    spaceInlineLoose: 12.0,
    spaceComponentGap: 8.0,
    spaceComponentSm: 16.0,
    spaceComponentMd: 24.0,
    spaceComponentLg: 32.0,
    spaceGroup: 16.0,
    spaceGroupLg: 32.0,
    spaceBlock: 16.0,
    spaceBlockLg: 32.0,
    spaceSection: 32.0,
    spaceSectionLg: 64.0,
    screen: 375.0,
  );

  static const tablet = FigmaSpacing(
    spaceInlineTight: 4.0,
    spaceInline: 8.0,
    spaceInlineLoose: 12.0,
    spaceComponentGap: 16.0,
    spaceComponentSm: 24.0,
    spaceComponentMd: 32.0,
    spaceComponentLg: 48.0,
    spaceGroup: 16.0,
    spaceGroupLg: 32.0,
    spaceBlock: 16.0,
    spaceBlockLg: 32.0,
    spaceSection: 32.0,
    spaceSectionLg: 64.0,
    screen: 640.0,
  );

  /// Retrieve the nearest [FigmaSpacing] from the widget tree.
  static FigmaSpacing of(BuildContext context) {
    return Theme.of(context).extension<FigmaSpacing>()!;
  }

  @override
  FigmaSpacing copyWith({
    double? spaceInlineTight,
    double? spaceInline,
    double? spaceInlineLoose,
    double? spaceComponentGap,
    double? spaceComponentSm,
    double? spaceComponentMd,
    double? spaceComponentLg,
    double? spaceGroup,
    double? spaceGroupLg,
    double? spaceBlock,
    double? spaceBlockLg,
    double? spaceSection,
    double? spaceSectionLg,
    double? screen,
  }) {
    return FigmaSpacing(
      spaceInlineTight: spaceInlineTight ?? this.spaceInlineTight,
      spaceInline: spaceInline ?? this.spaceInline,
      spaceInlineLoose: spaceInlineLoose ?? this.spaceInlineLoose,
      spaceComponentGap: spaceComponentGap ?? this.spaceComponentGap,
      spaceComponentSm: spaceComponentSm ?? this.spaceComponentSm,
      spaceComponentMd: spaceComponentMd ?? this.spaceComponentMd,
      spaceComponentLg: spaceComponentLg ?? this.spaceComponentLg,
      spaceGroup: spaceGroup ?? this.spaceGroup,
      spaceGroupLg: spaceGroupLg ?? this.spaceGroupLg,
      spaceBlock: spaceBlock ?? this.spaceBlock,
      spaceBlockLg: spaceBlockLg ?? this.spaceBlockLg,
      spaceSection: spaceSection ?? this.spaceSection,
      spaceSectionLg: spaceSectionLg ?? this.spaceSectionLg,
      screen: screen ?? this.screen,
    );
  }

  @override
  FigmaSpacing lerp(covariant FigmaSpacing? other, double t) {
    if (other == null) return this;
    return FigmaSpacing(
      spaceInlineTight: spaceInlineTight + (other.spaceInlineTight - spaceInlineTight) * t,
      spaceInline: spaceInline + (other.spaceInline - spaceInline) * t,
      spaceInlineLoose: spaceInlineLoose + (other.spaceInlineLoose - spaceInlineLoose) * t,
      spaceComponentGap: spaceComponentGap + (other.spaceComponentGap - spaceComponentGap) * t,
      spaceComponentSm: spaceComponentSm + (other.spaceComponentSm - spaceComponentSm) * t,
      spaceComponentMd: spaceComponentMd + (other.spaceComponentMd - spaceComponentMd) * t,
      spaceComponentLg: spaceComponentLg + (other.spaceComponentLg - spaceComponentLg) * t,
      spaceGroup: spaceGroup + (other.spaceGroup - spaceGroup) * t,
      spaceGroupLg: spaceGroupLg + (other.spaceGroupLg - spaceGroupLg) * t,
      spaceBlock: spaceBlock + (other.spaceBlock - spaceBlock) * t,
      spaceBlockLg: spaceBlockLg + (other.spaceBlockLg - spaceBlockLg) * t,
      spaceSection: spaceSection + (other.spaceSection - spaceSection) * t,
      spaceSectionLg: spaceSectionLg + (other.spaceSectionLg - spaceSectionLg) * t,
      screen: screen + (other.screen - screen) * t,
    );
  }

  @override
  int get hashCode {
    return Object.hash(
      spaceInlineTight,
      spaceInline,
      spaceInlineLoose,
      spaceComponentGap,
      spaceComponentSm,
      spaceComponentMd,
      spaceComponentLg,
      spaceGroup,
      spaceGroupLg,
      spaceBlock,
      spaceBlockLg,
      spaceSection,
      spaceSectionLg,
      screen,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FigmaSpacing) return false;
    return spaceInlineTight == other.spaceInlineTight && spaceInline == other.spaceInline && spaceInlineLoose == other.spaceInlineLoose && spaceComponentGap == other.spaceComponentGap && spaceComponentSm == other.spaceComponentSm && spaceComponentMd == other.spaceComponentMd && spaceComponentLg == other.spaceComponentLg && spaceGroup == other.spaceGroup && spaceGroupLg == other.spaceGroupLg && spaceBlock == other.spaceBlock && spaceBlockLg == other.spaceBlockLg && spaceSection == other.spaceSection && spaceSectionLg == other.spaceSectionLg && screen == other.screen;
  }
}

class _FigmaAvataAccessor {
  const _FigmaAvataAccessor();

  FigmaAvata get desktop => FigmaAvata.desktop;
  FigmaAvata get mobile => FigmaAvata.mobile;
  FigmaAvata get tablet => FigmaAvata.tablet;

  /// Retrieve [FigmaAvata] from the nearest [Theme].
  FigmaAvata of(BuildContext context) => FigmaAvata.of(context);
}

class _FigmaIconAccessor {
  const _FigmaIconAccessor();

  FigmaIcon get desktop => FigmaIcon.desktop;
  FigmaIcon get mobile => FigmaIcon.mobile;
  FigmaIcon get tablet => FigmaIcon.tablet;

  /// Retrieve [FigmaIcon] from the nearest [Theme].
  FigmaIcon of(BuildContext context) => FigmaIcon.of(context);
}

class _FigmaImageAccessor {
  const _FigmaImageAccessor();

  FigmaImage get mobile => FigmaImage.mobile;
  FigmaImage get tablet => FigmaImage.tablet;

  /// Retrieve [FigmaImage] from the nearest [Theme].
  FigmaImage of(BuildContext context) => FigmaImage.of(context);
}

class _FigmaSpacingAccessor {
  const _FigmaSpacingAccessor();

  FigmaSpacing get desktop => FigmaSpacing.desktop;
  FigmaSpacing get mobile => FigmaSpacing.mobile;
  FigmaSpacing get tablet => FigmaSpacing.tablet;

  /// Retrieve [FigmaSpacing] from the nearest [Theme].
  FigmaSpacing of(BuildContext context) => FigmaSpacing.of(context);
}

/// Top-level accessor for all Figma token collections.
class Figma {
  Figma._();

  static const avata = _FigmaAvataAccessor();
  static const icon = _FigmaIconAccessor();
  static const image = _FigmaImageAccessor();
  static const spacing = _FigmaSpacingAccessor();

  // --- Mode presets (all collections at once) ---

  static List<ThemeExtension> get desktop => [FigmaAvata.desktop, FigmaIcon.desktop, FigmaSpacing.desktop];
  static List<ThemeExtension> get mobile => [FigmaAvata.mobile, FigmaIcon.mobile, FigmaImage.mobile, FigmaSpacing.mobile];
  static List<ThemeExtension> get tablet => [FigmaAvata.tablet, FigmaIcon.tablet, FigmaImage.tablet, FigmaSpacing.tablet];
}

// --- BuildContext extensions ---

extension FigmaAvataContext on BuildContext {
  FigmaAvata get avata => FigmaAvata.of(this);
}

extension FigmaIconContext on BuildContext {
  FigmaIcon get icon => FigmaIcon.of(this);
}

extension FigmaImageContext on BuildContext {
  FigmaImage get image => FigmaImage.of(this);
}

extension FigmaSpacingContext on BuildContext {
  FigmaSpacing get spacing => FigmaSpacing.of(this);
}

